### ISSUE TITLE
trouble staging on rhobot.net Vue.js/webpack

### ISSUE THREAD

**Issue by jimscarver** [sceenius/DigLifePortal#3]
The portal runs fine on codesandbox but the package.json does not include any of the dev dependencies.
Our problem building on node.js with Vue.js and webpack.
Building it has been a nightmare we finally got it to run but the bundle.js is absent from the home page.

package.json
{
  "name": "diglife-portal-dev",
  "keywords": [],
  "dependencies": {
    "@johmun/vue-tags-input": "1.5.9",
    "acorn": "^6.0.5",
    "acorn-dynamic-import": "^4.0.0",
    "axios": "0.18.0",
    "babel-helper-vue-jsx-merge-props": "^2.0.3",
    "firebase": "5.5.9",
    "kinto-http": "4.6.1",
    "lodash": "4.17.11",
    "node-slack": "0.0.7",
    "particles.js": "2.0.0",
    "slugify": "1.3.4",
    "vue": "2.5.21",
    "vue-axios": "2.1.4",
    "vue-cookies": "1.5.7",
    "vue-markdown": "2.2.4",
    "vue-material": "1.0.0-beta-10.2",
    "webpack-dev-server": "^3.1.14"
  },
  "scripts": {
    "build": "webpack -d --watch"
  },
  "devDependencies": {
    "@webpack-cli/serve": "^0.1.3",
    "babel-core": "^6.26.3",
    "babel-loader": "^7.1.4",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-plugin-transform-vue-jsx": "^3.7.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "css-loader": "^2.0.1",
    "js-beautify": "^1.6.14",
    "style-loader": "^0.23.1",
    "vue-loader": "^15.4.2",
    "vue-style-loader": "^4.1.2",
    "vue-template-compiler": "^2.5.21",
    "webpack": "^4.14.0",
    "webpack-cli": "^3.1.2"
  },
  "description": "This is NOT in sync with GitHub."
}

**Comment by Silver-Wulf** [comment]
@jimscarver Is the package.json you posted the one that you are using that did not work or is that a working version?

**Comment by jimscarver** [comment]
@aviationhacker worked around the issue to build a dev version that runs. I expect he will succeed with the prod version also. I will close the issue for now.
